export { CMS_CONFIG_TEMPLATE } from './cms-config'
export { API_ROUTE_TEMPLATE } from './api-route'
export { DASHBOARD_PAGE_TEMPLATE } from './dashboard-page'
export { WRITER_LAYOUT_TEMPLATE } from './writer-layout'
export { AUTO_DRAFT_SCRIPT_TEMPLATE } from './auto-draft-script'
export { VERCEL_CRON_ROUTE_TEMPLATE } from './vercel-cron-route'